name: Validate registry.json

on:
  push:
    paths:
      - 'registry.json'

permissions:
  contents: read
  issues: write

jobs:
  validate-json:
    name: Validate registry.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./registry.schema.json
          INPUT_JSONS: ./registry.json
  create-bug:
    name: Create GitHub issue
    runs-on: ubuntu-latest
    needs: [ validate-json ]
    if: ${{ always() && (needs.validate-json.result != 'success') }}
    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE/invalid-registry-json.md
